FROM python:3.6-slim-stretch
WORKDIR /opt/src
COPY requirements_common.txt .
RUN pip install --no-cache -r requirements_common.txt && pip install --no-cache torch torchvision
CMD ["sh","-c", "jupyter notebook --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]